version: '3'

services:
  whatsapp-api:
    build:
      context: .
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_TOKEN=${API_TOKEN}
      - NODE_ENV=production
    volumes:
      - whatsapp-auth:/app/.wwebjs_auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  whatsapp-auth:
    driver: local 