version: '3'

services:
  whatsapp-api:
    build:
      context: .
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_TOKEN=${API_TOKEN}
      - NODE_ENV=production
      - TZ=Europe/Rome
    volumes:
      - whatsapp-auth:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
      - /tmp/puppeteer_data:/tmp/puppeteer_data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
    cap_add:
      - SYS_ADMIN

networks:
  app-network:
    driver: bridge

volumes:
  whatsapp-auth:
    driver: local
  whatsapp-cache:
    driver: local 